# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

silent: true

tasks:
  serve:
    cmds:
      - hugo serve -D

  new:
    cmds:
      - hugo new content post/{{.CLI_ARGS}}.md
    desc: Create a new post.

  default:
    cmds:
      - task: serve
